### ISSUE TITLE
findNhoodMarkers() error

### ISSUE THREAD

**Issue by ainarill** [MarioniLab/miloR#131]
Hi again!
I was trying to identify signatures of DA subpopulations in my data and when using the findNhoodMarkers() function i get the following error:

dge_smp <- findNhoodMarkers(data_milo, data_res,
                                     assay = "counts", gene.offset = FALSE, da.fdr = 0.1,
                                     aggregate.samples = TRUE, sample_col = "sample",
                                     subset.nhoods = data_res$annotation_group %in% c("Mast", "Macrophage", "DC")
                                     )

Found 48 DA neighbourhoods at FDR 10%
nhoodAdjacency found - using for nhood grouping
Error in .group_nhoods_from_adjacency(nhoods(x), nhood.adj = nhoodAdjacency(x),  : 
  unused argument (subset.nhoods = subset.nhoods)

I don't know what I'm doing wrong, any help or suggestion would be welcome!
Thanks.

**Comment by emdann** [comment]
Hi @ainarill 
Thanks for reporting, that is entirely on us. We have recently refactored the downstream analysis functions, so that instead of grouping and testing in one  with `findNhoodMarkers` we know have two separate functions `groupNhoods` and `findNhoodGroupMarkers`. The new workflow is shown in [this vignette](https://github.com/MarioniLab/miloR/blob/master/vignettes/milo_gastrulation.Rmd) (which I see now is not rendered in the website). We need to add a patch and deprecation warning to `findNhoodMarkers`.  

Could I ask you to take a look at the new vignette and let me know if there's anything unclear? We'd really appreciate feedback on this new functionality.

**Comment by MikeDMorgan** [comment]
Hi @ainarill We are currently doing a bit of a re-factor that will eventually deprecate`findNhoodMarkers`. Whilst we fix this, for now you can download/build from the `fix_test_groups` branch: 
```
devtools::github_install("https://github.com/MarioniLab/miloR", ref="fix_test_groups")
```
Note: devtools doesn't seem to build the documentation locally. Therefore, on the command line clone the specific branch and build locally to get the full documentation:
```
git clone --branch fix_test_groups https://github.com/MarioniLab/miloR
```

The relevant function will then be `findNhoodGroupMarkers`, after running `groupNhoods`.

**Comment by ainarill** [comment]
I ran `groupNhoods` and `findNhoodGroupMarkers` afterwards and everything is working perfectly, thank you so much!

**Comment by MikeDMorgan** [comment]
Glad it worked.
