### ISSUE TITLE
Evaluate proper neighborhood size

### ISSUE THREAD

**Issue by rtoddler** [MarioniLab/miloR#160]
Hi, 

In your mouse gastrulation tutorial, you suggest to evaluate if k defined by user is appropriate by plotNhoodSizeHist function.
My question is, what is the appropriate range (or distribution) of the neighborhood size saying I have 8 samples and a total of 21k cells?

Thanks!

**Comment by MikeDMorgan** [comment]
Hi @rtoddler Thanks for your question. Generally speaking we would recommend having a mean number of cells per neighbourhood at ~5 X samples, so in you case 40 cells per neighbourhood should give reasonable results. We generally find that between 30-60 cells per neighbourhood with 3-4 replicates per condition gives good results (this will be included in the manuscript when it is finished with peer-review).

**Comment by lindsaynhayes** [comment]
In the vignette you mention "We will later use some heuristics to evaluate whether the value of k
 should be increased." Is this available yet? I'm curious how I can evaluate the chosen k value (and prop). I was wanting advice on how to optimize the total number of neighborhoods (`nrows(da_results)`) and the size of the neighborhoods (Nhood size). Similar to how the d can be optimized by an elbowPlot or percent variance explained. For example, I have 18 samples (5 *18 = 90), then I want a Nhood size of 90 or a k = 90? Because a k = 90 is giving me 200-400 Nhood size. Should I decrease my k until I get an average Nhood size of 90? Does the total number of cells change this calculation?

**Comment by MikeDMorgan** [comment]
Hi @lindsaynhayes Thanks for your question and pointing out the omission in the vignette - we'll fix this on the next release. For now, a nhood size ~90 should give a reasonable balance between power and resolution. It's also probably worth keeping nhood size ~50 as a lower bound with this number of samples, such that you have at least 3-5 counts per nhood and sample. 

I hope that makes sense?

**Comment by lindsaynhayes** [comment]
Thanks!
