### ISSUE TITLE
How to interpret differential abundance with positive and negative log fold change within one cluster?

### ISSUE THREAD

**Issue by mihem** [MarioniLab/miloR#180]
Thanks for this great package, this approach is extremely helpful I think.

In one dataset I struggle with the interpretation of the data

![image](https://user-images.githubusercontent.com/46907494/136570586-db84fbd9-adc8-4be2-aab5-0e086f49bf8e.png)

So how do you interpret the CD8TEM cluster? There seems to be ~50% of that clusters enriched in one condition and ~50% enriched in the other condition.
How do you get the barcodes of the cells with the matching fold change? My idea would be to categorize the cells into two groups dependent on their abundance, highlight them in the UMAP to see where they are located and do DE gene analysis?

Thanks!
Mischko

**Comment by emdann** [comment]
Hi Mischko, Thank you for your interest in using our package! 

It's not uncommon to see subsets of neighbourhoods with both directions of DA fold-change within the same cluster. The interpretation would be that within the same cell population there are distinct subpopulations associated with condition and control. 

What I find a bit odd in the plot you shared is that you have very little neighbourhoods with no significant difference between conditions (unless you filtered out some neighbourhoods already?). This KNN graph seems to violate one of the underlying assumptions of the GLM model used for differential abundance testing i.e. that there is differential abundance in less than 50% of cells. How do these clusters look in a UMAP? Are you sure you don't have a residual batch effect between cells in condition 1 and condition 2? 

> How do you get the barcodes of the cells with the matching fold change? 

You can extract the cells belonging to each neighbourhood using `nhoods(milo_obj)`. This stores a binary matrix matching cells to neighbourhoods.

**Comment by emdann** [comment]
Hi Mischko, based on that UMAP embedding I find it slightly odd that there is such a pronounced difference between condition 1 and 2 in the CD8TEM population. How many replicates for each condition do you have? Have you tried running the test including the batch covariate as confounder in the model, to make sure that's not driving that large difference? You can do that by adding the batch identity as a column in `design.df` and running:
```
milo_res <- testNhoods(milo_obj, design='~batch_id+condition', design.df=design.df)
```

A value for logFC is assigned to each neighbourhood and stored in the `logFC` columns of the `milo.res` data.frame:
```
data(sim_trajectory)
milo.meta <- sim_trajectory$meta
milo.obj <- Milo(sim_trajectory$SCE)

milo.obj <- buildGraph(milo.obj, k=20, d=30)
milo.obj <- makeNhoods(milo.obj, k=20, d=30, refined=TRUE, prop=0.2)

milo.obj <- calcNhoodDistance(milo.obj, d=30)
milo.obj <- countCells(milo.obj, samples="Sample", meta.data=milo.meta)

milo.design <- as.data.frame(xtabs(~ Condition + Sample, data=milo.meta))
milo.design <- milo.design[milo.design$Freq > 0, ]
rownames(milo.design) <- milo.design$Sample
milo.design <- milo.design[colnames(nhoodCounts(milo.obj)),]

milo.res <- testNhoods(milo.obj, design=~Condition, design.df=milo.design)
head(milo.res)
```
If you want to find the cells assigned to a particular set of neighbourhoods (which you can select by logFC or cell type label, FDR etc etc), you can run something like:
```
library(Matrix)

my_nhoods <- milo.res$Nhood[milo.res$SpatialFDR < 0.01]
my_cells_ixs <- which(rowSums(nhoods(milo.obj)[,my_nhoods]) >= 1)
my_cells <- colnames(milo.obj)[my_cells_ixs]
```
However, it's not exactly straightforward (or meaningful?) to assign a single value of logFC to each cell, because cells can belong to multiple neighbourhoods.

**Comment by mihem** [comment]
Sorry, any further help on that @emdann @MikeDMorgan  ? 
Thank you!

**Comment by emdann** [comment]
thanks for the ping @mihem, I had missed the reply.  

>  don't think it's possible to integrate sample as a batch effect then? But do I have a systematic bias in my results then?

If the "sample" in the table above is the covariate you use for batch correction with Harmony then yes, there is a systematic bias that you can't correct for in the Milo test: if your integration is over-correcting the differences between PostCOVID and IIH samples you might be missing some biological variation in the integrated KNN graph. You'll have to make sure you are not overcorrecting before the differential abundance analysis. 

> Well my rationale is: Some of the clusters habe differential abundance in both directions. As you said in your first posts this suggests distinct subpopulations. I would like to characterize those subpopulations then. How would you approach that?

I would compare the cells in neighbourhoods with `SpatialFDR < 0.1 & logFC < 0` and the cells in neighbourhoods with `SpatialFDR < 0.1 & logFC > 0`, which effectively represent the two transcriptionally distinct subpopulations. We implement some helper functions to perform this type of comparison, see an example in [our vignette](https://bioconductor.org/packages/release/bioc/vignettes/miloR/inst/doc/milo_gastrulation.html#5_Finding_markers_of_DA_populations).

> For the calcNhoodDistance you use batch corrected pca, so would this then be harmony embeddings? (sorry for being off topic)

Yes, any reduced dimension space that you use for KNN graph construction and UMAP embedding. I am not familiar with the data objects used by Harmony, but in Seurat objects you should find it somewhere in `seurat.obj@reductions`. If you weren't using the corrected dimensions until now, this might explain the odd results in differential abundance analysis, which look like you would get if trying to run milo without batch correction.

**Comment by mihem** [comment]
Thanks!

I did use the harmony, so corrected, embeddings, so I don't think this explains the odd results. Yet true, the integration might be over-correcting.
Okay, I will try that approach, thanks!

**Comment by tkapello** [comment]
Just to add one silly question based on this example: which condition do the fold changes correspond to? In other words, a positive log fold change refers to neighborhoods more abundant in which level of the comparison? How are these levels defined?

**Comment by mastorkia** [comment]
I am coming with the same question as @tkapello. How is the reference dataset determined? I tried to change the order of the samples in the df for the model but I am getting same results.  @emdann

**Comment by MikeDMorgan** [comment]
If you have a pair-wise comparison then the comparison is based on the native ordering in R, which for a character or factor vector is lexicographical. For factor variables you can define these explicitly or use the `relevel` function to change the reference level. If your variable has >2 levels/unique values then the comparison will be between the reference level and the _last_ level because the default behaviour inside `testNhoods` is to take the last column of the model matrix as the comparison. You can set the explicit comparison using contrasts <- I am in the process of writing a vignette to better explain contrasts and their use in Milo. In the mean time, if you are interested, there are numerous threads relating to edgeR and limma w.r.t. defining and working with contrasts.
