### ISSUE TITLE
Visualization of plotNhoodGraphDA() with multiple conditions

### ISSUE THREAD

**Issue by DennisFeige** [MarioniLab/miloR#215]
Hi all,

thanks for the package. It seems quite useful!

I have a situation where I compare multiple conditions simialar to [your vignette](https://github.com/MarioniLab/miloR/blob/devel/vignettes/milo_contrasts.Rmd). At the end of your vignette you show that there is an enrichment in some neighborhoods comparing 1 condition to the rest on a plotNhoodGraphDA().

I would like to basically show the same graph but at the same time show condtion1 vs. treatment A, condtion1 vs. treatment B and  condtion1 vs. treatment C. I was thinking about how I could do that but couldn't come up with any good ideas. Is it eg. possible to implement color coding on plotNhoodGraphDA() (and then only show the condtion with the highest Log2FC)?
Do you have any other ideas?
...also fine if you don't.

Best,
Dennis

**Comment by MikeDMorgan** [comment]
Hi Dennis - it sounds like the clearest way to show these results would be to show a plot for each comparison. You can also plot the logFC for each comparison against each other because there will be a logFC for each nhood over multiple comparisons - a simple scatter plot would show where there is concordant changes along the diagonal, and discordant changes on the off-diagonal.

**Comment by DennisFeige** [comment]
Hi Mike,

okay, thanks. That was also the solution I thought about so far.

Best,
Dennis
