### ISSUE TITLE
testDiffExp potential issue

### ISSUE THREAD

**Issue by gianfilippo** [MarioniLab/miloR#236]
Hi,

I have a dataset with 3 biological replicates (2 cell states and 2 perturbations each): cellstate levels: A,B; pert levels: H,L. 
So, in total I have 12 samples (3 replicates by 4 conditions)
We are interested in HvsL in A and B. AvsB is not interesting
It is a paired design, since each biological replicate has A, B, H and L
I created a group variable as A.L, A.H, B.L, B.H and I have a sample variable: smp1, smp2, smp3 (biological replicates)

I also have 
isig = da_results$SpatialFDR<0.05
nhgrp = unique(da_results$NhoodGroup[isig]) # THIS IS A SINGLE NHOODGROUP
subset.nhoods = da_results$NhoodGroup==nhgrp & da_results$SpatialFDR<0.05

I then run the testDiffExp as follow:
dge <- testDiffExp(x, da_results, design = ~ 0 + Group + individualID, meta.data = data.frame(colData(x)),
                       model.contrasts = "GroupA.H - GroupA.L", subset.nhoods=subset.nhoods, assay = "counts")

which results in the following error:
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent

I traced this error to your perform_counts_dge

If I run the same code with assay = "logcounts" it works.
I checked the input to the perform_counts_dge and dimensionally, everything look then same between "counts" and "logcounts"

I am not sure what the difference is between perform_counts_dge and perform_logcounts_dge

Is there anything I am doing wrong ?
Also, it is unclear to me whether testDiffExp aggregates counts by biological replicate or not. Could you please clarify ?

I should add that I start with an "integrated" Seurat object x.Seurat (after running a Seurat based pipeline, including FindNeighbors)
I then do the following
DefaultAssay(x.seurat) <- "RNA"
x.sce <- as.SingleCellExperiment(x.seurat)
x <- Milo(x.sce)
graph(x.milo) = graph(buildFromAdjacency(x.seurat@graphs[[1]],is.binary=T))
I then copy the PCA and integrated UMAP from Seurat to Milo:
reducedDim(x.milo,type="pca") = x.seurat[["pca"]]@cell.embeddings
reducedDim(x.milo,type="integrated_umap") = x.seurat[["integrated_umap"]]@cell.embeddings
followed by 
x.milo <- countCells(x.milo, meta.data = data.frame(colData(x.milo)), sample="sampleID")
x.milo <- calcNhoodDistance(x.milo, d=50, reduced.dim="integrated_umap")
x.milo <- buildNhoodGraph(x.milo)
da_results = testNhoods(x.milo, design = ~ 0 + Group + individualID, design.df = designmat,
                                           model.contrasts = "GroupA.H - GroupA.L", fdr.weighting="graph-overlap", 
                                           reduced.dim=dimred)

Thanks in advance for any help

Best

**Comment by emdann** [comment]
Hi @gianfilippo 

Could you just clarify that you trying to find DE genes between condition H and L _within_ the same nhood group?  
The function `testDiffExp` is a wrapper we wrote in an initial implementation, but we are not maintaining it at the moment (I will add a deprecation notice) because we are usually interested in finding DE genes _between_ nhoods and nhood groups, which is implemented in `findNhoodGroupMarkers` and exemplified in the [vignette](https://rawcdn.githack.com/MarioniLab/miloR/7c7f906b94a73e62e36e095ddb3e3567b414144e/vignettes/milo_gastrulation.html#5_Finding_markers_of_DA_populations). 

The reasoning is that if you detect differential abundance in a neighbourhood that means you have lots more cells in condition H than condition L, so the differential expression test between conditions will be very imbalanced in these neighbourhoods. DE _within_ neighbourhoods would be more relevant in nhoods that are _not_ DA, but this poses some unique challenges, which another project in the lab is currently tackling.

**Comment by emdann** [comment]
closing as duplicated in https://github.com/MarioniLab/miloR/issues/237

**Comment by gianfilippo** [comment]
Hi,

thanks.  Yours is a good point, I will look in the markers direction with findNhoodGroupMarkers.

Best
