### ISSUE TITLE
Seeking advice for downstream analysis of significantly DA neighborhoods

### ISSUE THREAD

**Issue by dgagler** [MarioniLab/miloR#241]
Hi, great package guys. Thanks for making it and being involved with the community.

I've analyzed some scRNA data with it and have gone through the "standard workflow" to produce differentially abundant neighborhoods. I'm interested now, however, in the subset of neighborhoods that are significantly DA. Specifically, I'm interested in exploring what makes them transcriptionally different from the insignificant neighborhoods of the same cell type.

As such, I have a few questions:

1. If I'm interested in testing differential expression between 2 groups (assigned to the NhoodGroup col as "significant" and "insignificant") for only a single cell type, should I be subsetting my milo object? I've been subsetting my results df to only include my cell of interest, assigning the NhoodGroup column as desired, and then using that for the da.res variable in findNhoodGroupMarkers. Is this best practice for doing something like this?
2. Using the above approach, I've generated a heatmap for a subset of cells, comparing neighborhoods I've defined as either "signif" or "insignif". The heatmap columns seemed to be switched from what comes out of findNhoodGroupMarkers. For example, the MT1G has computed logFC of 0.22 in my significant group (and, as such, -0.22 logFC in my insignificant group), yet the heatmap shows higher expression of MT1G in the insignificant group. See attached images of heatmap and the table I'm using for the da.res parameter. Is it possible that this is labeling bug? Is there a way to change these labels? Am I missing something?

![NK_SignifInsignif_Heatmap](https://user-images.githubusercontent.com/31450828/194159672-f2e1c737-d0f6-433f-a205-98bdaa6364dd.png)
![table](https://user-images.githubusercontent.com/31450828/194160039-2b16bde1-b255-4f58-8391-de1c104ef4d1.png)

3. When would you NOT set aggregate.samples = true?

Furthermore, I'd be interested (and I assume others would also) in any general suggestions or best practices for comparing significant/insignificant neighborhood populations within a particular cell type that you guys might have.

Hope this is all clear! Apologies if not or if I'm missing some best practices, first time asking a Q on here. Let me know if there's anything else I can provide to make this coherent/proper!

Thanks,
Dylan

**Comment by MikeDMorgan** [comment]
Hi @dgagler  - thanks for using Milo. Firstly, when reporting an issue you should always present exactly the code that you have used, otherwise there is too much guess work involved on our part as to what and where the issue in the code is.

If you are only interested in comparing the 2 groups then you can perform the subsetting in the `findNhoodGroupMarkers` function by passing a vector as `subset.nhoods=myvector` as described in the docs. You can then combine this with `subset.groups=c("significant", "insignificant")` to the get the desired behaviour.

I suspect that you have an unintuitive result in your marker genes because of the way that character vectors are treated in the model matrix used for the statistical testing in the marker identification. By default it will set the lexographically ordered first element as the control level, which in this case would be "insignif", so the logFC and gene expression actually agree with each other just fine. You need to set the factor levels in your `da.res` dataframe column explicitly to get the logFC for the signif/insignif as you are expecting it.

**Comment by dgagler** [comment]
Hi Mike. This all makes sense and is very helpful. Thanks!

And in regards to setting aggregate.samples = TRUE...are there any circumstances under which you would not set this?

**Comment by MikeDMorgan** [comment]
From a statistical point of view - not at the moment. The consensus at the moment is to do this type of analysis by pseudobulking first rather than treating single-cells as replicates, which violates the i.i.d. assumption of many statistical model (the independent bit). We allow some lee-way as we might (or might not) introduce a model later that models the dependence between single-cells from the same experimental sample. From the single-cell QTL field this doesn't usually give many gains over pseudo-bulking, so it's not a priority. As for doing this at the level of nhoods - it's massively complicated by the fact that cells are members of multiple nhoods, so would not be something we look into anytime soon.

**Comment by dgagler** [comment]
Thanks for clarifying and for the thorough explanation. (Hopefully) last question: 

Is the fact that cells are members of multiple nhoods violating the i.i.d. assumption in the same way that pseudobulking is? Or are these 2 different problems of independence?

**Comment by MikeDMorgan** [comment]
These are 2 different problems that introduce dependence between the observations - pseudobulking solves the issue with using single-cells as replicates. The issue with having a cell contribute to multiple nhoods is that it essentially becomes a problem of making exactly the same measurement multiple times - again, the trivial solution is to just not do this. In fact, you would also have to still take into account the fact that the cells are not independent measurements in a non-trivial way.

So putting it simply - pseudobulk, it's easy and intuitive.

**Comment by dgagler** [comment]
Sorry for pushing on this! I'm probably missing something here. I'm on board with pseudobulking being the right move but it's still not clear to me that pseudobulking by sample/replicate and pseudobulking by neighborhood are fundamentally different.

For example, if I were to annotate my cells by their assigned neighborhood and then use this as the input for the sample_col variable when pseudobulking with findNhoodGroupMarkers...how is this different from pseudobulking by sample/replicate? In both cases you are averaging expression and still avoiding treating single cells as replicates, right? Thanks again!

**Comment by MikeDMorgan** [comment]
If you pseudobulk by nhood then you don't remove the dependency caused by the fact that the single cells are sample _from the same experimental sample_.
