### ISSUE TITLE
Nhoodgroups change when code is re-run

### ISSUE THREAD

**Issue by caitsimop** [MarioniLab/miloR#261]
Hi! 

Just as the title of the issue suggests, my neighbourhood groups changed when I reran my script with no other changes. I'm wondering if this is expected behaviour? 

If so, my suggestion is to add an internal call to `set.seed()` that has a default number and can be adjusted by the user if needed.

**Comment by emdann** [comment]
Hi @caitsimop, the `groupNhood` function relies on the Louvain clustering implementation in [igraph](https://igraph.org/r/doc/cluster_louvain.html), which relies on setting a seed. 

Following the [Bioconductor developer guidelines](https://www.bioconductor.org/developers/package-guidelines/), `set.seed` is never used in any internal code. This should be set by the user before running the function to ensure reproducibility.

**Comment by szhorvat** [comment]
Since igraph 1.3, the Louvain implementation is randomized. This is intentional, and helps users determine whether their results are robust. If the results vary _significantly_ across runs, then there isn't a very well defined community structure in the network, and you should not read too much into the result.
