### ISSUE TITLE
effect of k and N of PCs on DA analysis

### ISSUE THREAD

**Issue by gianfilippo** [MarioniLab/miloR#265]
Hi,

I am a bit puzzled on how to choose an optimal k for DA.
I start from a Seurat obj, and convert it to a Milo obj. My Seurat obj is a combined object of 12 samples (about 160k cells)
Specifically, I use the following
miloOBJ@graph = seuratOBJ@graphs
graph(miloOBJ) = graph(buildFromAdjacency(miloOBJ@graph[[clID]],is.binary=T,k=20))
miloOBJ <- makeNhoods(miloOBJ, prop=0.1, k=20, d=nPCs, refined=T, reduced_dims="pca")

Now, in my first analysis I used 50 PCs and got some DA results following your tutorial
In my second analysis, with the same data, I used 20 PCs and ended up with no significant DA.
As far as I understand, the graphs generated with 20 and 50 are different, and I assumed that a k=20 may not be optimal for case of 20 PCs. 
Looking at the NhoodSizeHist it looked like the mean size is around 45 or so. In your tutorial you have a few recommendations: 
a mean size between 50 and 100 
a peak distribution between 50 and 100 
an average neighbourhood size over 5 x N_samples (60 in my case)

I changed k, from 20 to 140 (see below), and the mean neighbourhood size change very little.
for (k in 20:40) {
  miloOBJ@graph = seuratOBJ@graphs
  graph(miloOBJ) = graph(buildFromAdjacency(miloOBJ@graph[[clID]], is.binary=T, k=k))
  miloOBJ <- makeNhoods(miloOBJ, prop=0.1, k=k, d=nPCs, refined=T, reduced_dims="pca")
  meank = mean(colSums(nhoods(miloOBJ)))
}

Is this behavior expected since I am using a pre-existing graph from the Seurat obj ? should I rather build a graph from scratch ?

How can you explain the effect of number of PCs on the DA analysis ? 

Thanks

**Comment by emdann** [comment]
Hi @gianfilippo, from your description my impression is that the difference between results with 20 or 50 PCs has more to do with the features of your dataset. My first guess would be that you have a batch/sample effect that is captured by the first PCs of your dataset. If that's the case it could be that taking 20 PCs many neighbourhoods contain cells from only a few samples, and this leads to no significant DA. You can check this by plotting the number of cells vs number of samples in each nhood.

My recommendation would be to perform some QC analysis on your reduced dimensions space before moving to differential abundance analysis, to assess whether the PCA is capturing batch effects (e.g. diagnostics from the [OSCA](http://bioconductor.org/books/3.16/OSCA.multisample/correction-diagnostics.html) book). Is this the same space/KNN graph you are using for other analyses such as UMAP embedding and cell type clustering? You might have to use reduced dimensions from a batch correction method instead of PCA as input for Milo analysis.

**Comment by gianfilippo** [comment]
Hi,

I have my QC already done, and clustering, markers, etc look good. 
Anyway, I will take a look at the number of cells vs number of samples.

Also, I used the PCA computed after integrating the samples (i.e. batch correction). This is what is used for the integrated_umap. Should I use the integrated_umap, instead ?

The mean neighborhood size changes very slowly with k. Is this a consequence of using a precomputed graph or is this expected ?  I am asking since k is described to affect DA power.

Thanks

**Comment by MikeDMorgan** [comment]
@gianfilippo - the UMAP is for purely visualisation purposes, the graph should always be built from the (integrated) reduced dimensions. If you are using a pre-computed graph, e.g. a WNN or SNN graph, then use the same `k` used for that initial graph for consistency.
