### ISSUE TITLE
testNhoods with multiple contrasts 

### ISSUE THREAD

**Issue by gianfilippo** [MarioniLab/miloR#271]
Hi,

In my design, I am interested in 2 contrasts, say, A - B, and C - D.
Running each contrast separately, I get 12 significant DA Nhoods with model.contrasts=c("A - B ")
Nhoods = 26 1379 1717 1933 3038 3039 3806 3873 3992 4077 4139 4408
and 5 significant DA Nhoods with model.contrasts=c("C - D ")
Nhoods = 373  818 1204 2594 4065

if I run the function testNhoods with the 2 contrasts at once 
model.contrasts=c("A - B","C - D"), 
I get 20 significant Nhoods.
Nhoods = 26  373  616  621  657  818 1379 1705 1717 1933 2346 3038 3039 3176 3806 3873 3992 4077 4139 4408
You can see that 
 616  621  657 1705 2346 3176
are present when running 2 contrasts, but not in the union of the individual contrasts.
Also,
1204 2594 4065
are present in the union of the individual contrasts. but not when running 2 contrasts together.

Am I not supposed to feed 2 contrasts art once ?

Thanks

**Comment by MikeDMorgan** [comment]
Hi @gianfilippo I'd recommend runnning each contrast separately for now, as the formal testing will only return the results for one contrast, not an omnibus test. If individual nhoods are either entering or leaving the "significant" set the it is probably because they are close to what ever threshold you are using.

**Comment by gianfilippo** [comment]
Ok, i asked because the the help function mentions a "string vector" and I assumed it would take a vector of contrasts.
Thanks for explaining

**Comment by wmacnair** [comment]
Hi, just following up on the recommendation to run contrasts separately. 

I think if the recommendation is not to run multiple contrasts at the moment, this should be made clear in the package messages and in the documentation. The safest option would be to not allow it until it is ready (although it should be pretty straightforward to add a loop, a `contrast` column and a call to `rbind`, I would assume?), but otherwise it should at least raise a warning.

Out of curiosity, if I run multiple contrasts, what test does the resulting PValue correspond to? Something like ANOVA?

Thanks!
Will

**Comment by MikeDMorgan** [comment]
Hi @wmacnair
This comes from the behaviour of `glmQLFTest` and `topTags` in edgeR, which computes (I assume) an omnibus p-value with multiple contrasts, which is what is fed into the spatialFDR correction, but returns a log fold change for each contrast. Note, the exact behaviour of multiple contrasts in  `glmQLFTest` is also undocumented, but was clarified by Gordon K Smyth here: https://support.bioconductor.org/p/117466/

I agree this should be documented better, and I will add it to the to-do list for the next Bioc release.

**Comment by wmacnair** [comment]
Hi @MikeDMorgan, thanks for your explanation :)

I'm wondering what the most common use case for specifying multiple contrasts would be. My expectation is that most users doing that would be interested in having separate p and FDR values for each contrast, rather than an omnibus p-value. If that's the case, then it could be worth adding an internal loop to get values for a list of contrasts.

Cheers
Will
