### ISSUE TITLE
could this packages support TSNE?

### ISSUE THREAD

**Issue by ZivTQ** [MarioniLab/miloR#284]
Hi
thanks for  your packages, it is really useful.
I have one problem when use it. 
My single cell data was generated using Seurat package and reduced using TSNE.
however, I got this error. I tested in different data, but the same error occured.
```
Warning in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE,  :
  did not converge--results might be invalid!; try increasing work or maxit
Error in if (xx != 0) xx/10 else z/10 : argument is of length zero
```
The code listed here:
```
A <- as.SingleCellExperiment(Mar)
A_milo <- miloR::Milo(A)#milo object构建
A_milo <- miloR::buildGraph(A_milo, k = 10, d = 50)
```
thanks 

sessionInfo()
```
 [1] ggpubr_0.6.0                dplyr_1.1.2                 stringr_1.5.0              
 [4] data.table_1.14.8           forcats_1.0.0               scales_1.2.1               
 [7] scater_1.24.0               scuttle_1.6.3               ggbeeswarm_0.7.2           
[10] SeuratWrappers_0.3.1        SingleCellExperiment_1.20.1 SummarizedExperiment_1.28.0
[13] Biobase_2.58.0              GenomicRanges_1.48.0        GenomeInfoDb_1.34.9        
[16] IRanges_2.32.0              S4Vectors_0.36.2            BiocGenerics_0.44.0        
[19] MatrixGenerics_1.10.0       matrixStats_1.0.0           ggplot2_3.4.2              
[22] RColorBrewer_1.1-3          SeuratObject_4.1.3          Seurat_4.3.0               
[25] miloR_1.9.1                 edgeR_3.38.4                limma_3.52.4  
```

**Comment by ZivTQ** [comment]
> Hi thanks for your packages, it is really useful. I have one problem when use it. My single cell data was generated using Seurat package and reduced using TSNE. however, I got this error. I tested in different data, but the same error occured.
> 
> ```
> Warning in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE,  :
>   did not converge--results might be invalid!; try increasing work or maxit
> Error in if (xx != 0) xx/10 else z/10 : argument is of length zero
> ```
> 
> The code listed here:
> 
> ```
> A <- as.SingleCellExperiment(Mar)
> A_milo <- miloR::Milo(A)#milo object构建
> A_milo <- miloR::buildGraph(A_milo, k = 10, d = 50)
> ```
> 
> thanks
> 
> sessionInfo()
> 
> ```
>  [1] ggpubr_0.6.0                dplyr_1.1.2                 stringr_1.5.0              
>  [4] data.table_1.14.8           forcats_1.0.0               scales_1.2.1               
>  [7] scater_1.24.0               scuttle_1.6.3               ggbeeswarm_0.7.2           
> [10] SeuratWrappers_0.3.1        SingleCellExperiment_1.20.1 SummarizedExperiment_1.28.0
> [13] Biobase_2.58.0              GenomicRanges_1.48.0        GenomeInfoDb_1.34.9        
> [16] IRanges_2.32.0              S4Vectors_0.36.2            BiocGenerics_0.44.0        
> [19] MatrixGenerics_1.10.0       matrixStats_1.0.0           ggplot2_3.4.2              
> [22] RColorBrewer_1.1-3          SeuratObject_4.1.3          Seurat_4.3.0               
> [25] miloR_1.9.1                 edgeR_3.38.4                limma_3.52.4  
> ```

However, if the data reduced using UMAP, every thing is OK!

**Comment by emdann** [comment]
Hi @ZivTQ 
The KNN graph construction step (`buildGraph`) should not use any dimensionality reduction used for visualization (such as tSNE or UMAP), but the reduced dimension space that you have used to build UMAP/tSNE themselves. By default this is PCA space, which should be stored in `reducedDim(A_milo, "PCA")`. 

I suspect that this error raises because you don't have a `reducedDim` named "PCA" and the function tries [to run PCA on the spot](https://github.com/MarioniLab/miloR/blob/1ecd56feefaa47e5fb64e46c1c704eba64c93c15/R/buildGraph.R#L111-L112), but there must be something wrong with the data stored in `logcounts(milo_A)`. It might be that running UMAP in Seurat makes some changes in the reduced dimensions or logcounts so that PCA can be run? 

What I would suggest is to check the name of the latent dimensions in your converted SCE object and specify the correct name with the `reduced.dim` parameter in `buildGraph`. You should use the same dimensions that you used to run UMAP (specified with `reduction` parameter in Seurat function `RunUMAP`).
