### ISSUE TITLE
Simple question "Can we add seurat_clusters"?

### ISSUE THREAD

**Issue by mckimcd177** [MarioniLab/miloR#287]
Hi, guys.
Thanks for developing this awesome package. Not sure if I can post this issue here. It's basically a problem for a newbie like me. 

Here is a brief history. My project is to compare healthy control and 4 different groups of patients with different stages of autoimmune disease, using scRNA-seq. I am trying to identify interesting cell types defining a certain stage of disease using Milo R package. With the user-friendly tutorial, I was able to draw this graph as below, although I did not understand 100% what it means. I found that the Non_JSS group looks interesting to me because this group showed different distributions on the dimensional plot. The next step was to identify what the cluster in this group is, which did not work for me, unfortunately. The problem occurred at this step; the code is not working and tried to solve this but failed. 
![test](https://github.com/MarioniLab/miloR/assets/112354348/aa0ae58a-d0bb-4a00-bb72-0258784ff147)
![test3](https://github.com/MarioniLab/miloR/assets/112354348/a98bcdef-4970-4df1-8a2e-776a11de8474)

Here are my codes.

> JSS.combined <- readRDS("JSS.combined.rds")
> JSS_sce <- as.SingleCellExperiment(JSS.combined) 
> JSS_meta <- JSS.combined@meta.data
> colData(JSS_sce) <- DataFrame(JSS_meta)
> logcounts(JSS_sce) <- log(counts(JSS_sce) + 1)
> JSS_sce <- runPCA(JSS_sce, ncomponents=30)
> JSS_sce <- runUMAP(JSS_sce)
> JSS_milo <- Milo(JSS_sce)
> reducedDim(JSS_milo, "UMAP") <- reducedDim(JSS_sce, "UMAP") 
> JSS_milo <- buildGraph(JSS_milo, k = 10, d = 30)
> JSS_milo <- makeNhoods(JSS_milo, prop = 0.1, k = 10, d=30, refined = TRUE)
> plotNhoodSizeHist(JSS_milo)
> JSS_milo <- countCells(JSS_milo, meta.data = as.data.frame(colData(JSS_milo)), sample="orig.ident")
> JSS_design <- data.frame(colData(JSS_milo))[,c("Subset","orig.ident","seurat_clusters")] # Problem looks start here
> JSS_design$seurat_clusters <- as.factor(JSS_design$seurat_clusters) 
> JSS_design <- distinct(JSS_design)
> rownames(JSS_design) <- JSS_design$orig.ident # This code does not work for me whatever I put in any columns in JSS_design.

It must be very simple but for me not. The error said "Duplicate 'row.names' are not allowed". Do you guys have any ideas regarding this issue? Hope someone like me watches this and gets some information for the future.

Thank you.

**Comment by MikeDMorgan** [comment]
Hi @mckimcd177 This is not strictly an issue with Milo. I would strongly recommend you make sure you are familiar with what all of the individual functions do in order to debug your problem. Importantly, don't blindly follow lines of code and assume they will work on your own data. If needs be, I would recommend a course in R that would allow you to develop your knowledge and skills in this area more, e.g. data camp R course or the excellent carpentries workshops: https://swcarpentry.github.io/r-novice-gapminder/

As a general note when submitting issues to repositories, make sure you post (a) the problem, (b) the code, (c) output of errors and (d) the output of `sessionInfo()`.
