### ISSUE TITLE
Cell Condition Relabelling Functionality

### ISSUE THREAD

**Issue by DarioS** [MarioniLab/miloR#325]
Once we have the neighbourhoods or groups, would it be a convenient to offer downstream functionality in the package? For example, let's say neighbourhood 3 is ten-fold enriched in the resistant-to-therapy condition. There are still a few cells belonging to patients who are labelled as sensitive in this group. Would it be convenient to provide a function which relabels all of the cells belonging to a neighbourhood group to the majority condition? Therefore, although each patient has only one starting label - either sensitive or resistant, after Milo analysis, they could have a proportion of cells with both condition labels. This would be useful for identifying samples with, for instance, 95% sensitive, 5% resistant cells. Or, in other words, which patients have disease that is likely to recur after treatment due to small cell subgroups which are unlikely to be killed by a therapy, based on their similarity to cells with opposite label.

**Comment by MikeDMorgan** [comment]
I think this could be a field-specific analysis, and hence I would encourage you to create your own functions that take Milo/DA results and compute this. Milo is designed to facilitate DA testing, and it is necessary to be quite strict with what functionality is contained in the package because it also needs to be maintained (Heng Li I am not).

**Comment by MikeDMorgan** [comment]
Heng Li's comment on software devel: http://lh3.github.io/2019/03/11/on-maintaining-bioinformatics-software

(Also, I'm sure both Aaron and I would gladly agree that I'm not Aaron).
