### ISSUE TITLE
plotNhoodExpressionDA - legend plotting positions obsucres labels

### ISSUE THREAD

**Issue by MikeDMorgan** [MarioniLab/miloR#58]
If labelled genes are at the top of a plot, the the legend overlaps them and they cannot be seen. Using the usual tricks outside of the function to adjust legend position does not work - I assume this is something to do with cowplot.  It would be better to either not gather the legends, or to have them positioned sufficiently far from the main plot to allow gene labeling at any row of the heatmap.

Example:
![MouseThymus_iTEC_heatmap](https://user-images.githubusercontent.com/6473398/97014534-5ef3e880-1542-11eb-9118-636c3eb267e4.png)

**Comment by emdann** [comment]
The plot is assembled using `patchwork`. The space between the collected legends and the plot can be modified changing the `legend.margin` parameter on the whole patchwork. This can be done by `&` a theme object as explained [here](https://github.com/thomasp85/patchwork/issues/136#issuecomment-561311450)

Example:
```
figure <- plotNhoodExpressionDA(liver_milo, milo_res, marker_genes, cluster_features = TRUE, 
                      alpha = 0.1,
                      scale_to_1 = TRUE,
                      subset.nhoods = milo_res$annotation_lineage=="Endothelia",
                      highlight_features = highlight_genes, show_rownames = FALSE
                      ) 
figure
```
![000006 (3)](https://user-images.githubusercontent.com/32264060/97162769-8f709800-1777-11eb-8a07-a157f50862a2.png)

```
figure & theme(legend.margin = margin(0,0,0,50))
```
![00000c (1)](https://user-images.githubusercontent.com/32264060/97162938-cf377f80-1777-11eb-9374-58a2aa486cfa.png)

In the function, I position the collated legends to the top right so that the overlap problem only comes up if you are highlighting the features in the first rows of the heatmap. I am not sure if I would hard code a `margin` parameter as above: if you are not highlighting anything or just genes in the middle of the heatmap you will end up with weird white space and an unnecessarily wide plot. What do you think? I could add a note explaining how to manipulate patchwork objects to a vignette demonstrating the use of downstream analysis functions.

**Comment by MikeDMorgan** [comment]
I think it would be preferable to have the space there all the time as there is no guarantee where gene labels will sit in the plot as their ordering is defined by the call to `hclust`. We have to assume that labels could be anywhere, and have a plot that is agnostic to that. I think having a legend that is slightly further out is a pretty small compromise - people can still adjust the legend if they want to themselves by setting their own `theme` values.

**Comment by emdann** [comment]
Fixed in https://github.com/MarioniLab/miloR/pull/66
