### ISSUE TITLE
Lack of documentation for testNhoods() output

### ISSUE THREAD

**Issue by pascaltimshel** [MarioniLab/miloR#81]
Dear authors,

First of all, the miloR package looks incredibly useful and generally well-documented. 

My issue is about the lack of documentation for the output table of `testNhoods()`. The documentation says `A data.frame of model results.` In order to use and interpret miloR results correctly, I find it important to understand the table. **Can you provide better documentation for the output table?**

A few specific questions to get started:
- What is `logFC`? What is its interpretation? How do you determine its 'direction'/'ratio' (FC=E7/E8 or the opposite)? (And does it make sense if analyzing > 2 experimental conditions (say E7, E7.5 and E8)
- What is `logCPM`?
- When is it appropriate to use `FDR` instead of `SpatialFDR`? (If ever)

Example output from the [Mouse gastrulation example
](https://raw.githack.com/MarioniLab/miloR/use_pkgdown/docs/articles/milo_gastrulation.html#testing-1) :
```
da_results <- testNhoods(embryo_milo, design = ~ sequencing.batch + stage, design.df = embryo_design)
da_results
##        logFC   logCPM        F       PValue         FDR Nhood  SpatialFDR
## 7  -7.397680 20.20389 13.18174 2.868468e-04 0.008307757     7 0.007518813
## 15 -7.407804 19.72189 14.72980 1.263205e-04 0.008307757    15 0.007518813
## 53  7.168031 19.37642 12.80220 3.510315e-04 0.008307757    53 0.007518813
## 64 -7.164631 19.67509 14.31767 1.570634e-04 0.008307757    64 0.007518813
## 69 -7.652294 19.96889 14.84507 1.188619e-04 0.008307757    69 0.007518813
## 71 -7.357238 19.56574 15.26142 9.542589e-05 0.008307757    71 0.007518813
```

**Comment by MikeDMorgan** [comment]
Hi Pascal,
Thanks for your interest in the package, and suggestion for improving the documentation.

To answer your specific questions:

>     * What is `logFC`? What is its interpretation? How do you determine its 'direction'/'ratio' (FC=E7/E8 or the opposite)? (And does it make sense if analyzing > 2 experimental conditions (say E7, E7.5 and E8)

`logFC` is the log fold change between conditions. For a comparison across ordered variables, as is the case for E7 - E8, then the interpretation of the logFC is the mean per-unit change in cell counts per change in predictor variable. So in the example above the first line of the table shows that there is an average 7-fold lower counts as you go from E7 to E7.5 to E8. In essence, you interpret it in the same way that you would a regression coefficient from any other linear model.

>     * What is `logCPM`?

Because we use `edgeR`, which was originally designed for RNA-seq differential expression testing, we get the `logCPM`, which is the log counts per million. In the case of `Milo` we can interpret this as the (log) average normalized cell counts for that neighbourhood across all samples, normalized by a scaling factor (the sum of al neighbourhood counts in that sample).
 
>     * When is it appropriate to use `FDR` instead of `SpatialFDR`? (If ever)

We would argue that you should always use the `SpatialFDR`, however, there may be instances where understanding the relationship between the standard Benjamini & Hochberg FDR procedure and the weighted FDR that we use is informative for users. You'll note that the unadjusted p-value is also included in the results table (`PValue`), as we prefer to report all 3 for transparency.

**Comment by pascaltimshel** [comment]
Great answers. Can't think of any more questions (for now), thanks!

**Comment by pascaltimshel** [comment]
Just to clarify "logFC is the log fold change between conditions": logFC is the _natural log_?

**Comment by MikeDMorgan** [comment]
Hi @pascaltimshel, yes that is correct. I think it's fair to say that `log` would be generally interpreted as the natural logarithm as there is no base specified.

**Comment by alikhuseynov** [comment]
Hi there, could we clarify that miloR results on `logFC` are natural log values or base 2? 
As we know, by default R is using a natural log but in `edgeR` it seems to be `log2`
have a look at these threads:
https://www.biostars.org/p/303806/
https://stat.ethz.ch/pipermail/bioconductor/2013-January/050311.html
thanks!

**Comment by MikeDMorgan** [comment]
I can confirm they are log2-fold changes as it uses the same output as edgeR

**Comment by edridgedsouza** [comment]
To clarify about the LogFC. My design formula is `~treatment_stage`, where `treatment_stage` is `PRE`, `ON`, or `POST`. Above, the examples use `E7`, `E7.5`, and `E8` as ordered variables, with positive LogFC corresponding to E8 and negative LogFC corresponding to E7, if I understand correctly. In my instance, what is the best way to ensure my `treatment_stage` is encoded properly? Should I:

A. Recode `PRE`, `ON`, `POST` as 1, 2, 3?

B. Keep the existing factor names but relevel them?

C. Perform only pairwise comparisons of PRE vs ON and ON vs POST for better interpretability?

Thanks

**Comment by MikeDMorgan** [comment]
Hi @edridgedsouza - always the first thing to ask is: what is your biological question? If you assume linearity across the 3 levels of your variable then encoding them as a factor with PRE < ON < POST would ensure that positive LFCs are more abundant in the direction of PRE -> ON -> POST, while negative LFCs would be in the opposite direction, i.e. PRE <- ON <- POST. This analysis would implicitly assume that the gap between PRE and ON is the same as ON and POST. 

If your question is whether there is a difference between PRE &ON and POST & ON or PRE & POST, then this necessitates a pair-wise analysis - best to create new dummy variables for this where you have 0 and 1 encoding the relevant levels.

__NB__: this is strictly a different question to the OP, so better to open it as a new issue in the future.
