### ISSUE TITLE
findNhoodMarkers batch correction

### ISSUE THREAD

**Issue by lucia-ramirez** [MarioniLab/miloR#82]
For gene expression signatures, is it better to have counts previously corrected by batch effect or just include them in the model? 

And also, is it possible to have sort of the intermediate output of findNhoodMarkers, where you have the list of cells that were grouped together regarding the da results and the design? I just want to check there is no further batch effect in those groups

Thanks

**Comment by emdann** [comment]
Hi Lucia. The `findNhoodMarkers` function expects counts or log-counts, I would recommend using raw counts and including the technical covariate in the experimental design of the test. Depending on the number of replicates you have you might want to specify `aggregate_samples=TRUE`. This allows to perform testing exploiting the replication structure in the experimental design, rather than treating single-cells as independent replicates. 

> And also, is it possible to have sort of the intermediate output of findNhoodMarkers, where you have the list of cells that were grouped together regarding the da results and the design?

You can specify `return.groups=TRUE` to get a `data.frame` of cell-to-group assignments.

**Comment by lucia-ramirez** [comment]
return.groups = TRUE returns a data.frame with sample_group and Nhod.Group but it doesn't contain any cell ID or other information to map them to the original dataset

**Comment by MikeDMorgan** [comment]
@emdann sample aggregation overwrites the output meta data, so that `return.groups=TRUE` and `aggregate.samples=TRUE` are incompatible.

**Comment by MikeDMorgan** [comment]
Hi @lucia-ramirez Do you have lots and lots of cells, or many, many samples? For now I'd recommend trying to run `findNhoodMarkers` with `return.groups=TRUE` and `aggregate.samples=FALSE` until we fix this, if it is urgent.

**Comment by MikeDMorgan** [comment]
Hi @lucia-ramirez could you pull in the latest version, or reinstall with `devtools::install_githib("MarioniLab/miloR)` and try again, with `return.groups=TRUE`, _and_ `aggregate.samples=TRUE`.
